def product_to_dict(row):
    return {
        'id': row['id'],
        'name': row['name'],
        'slug': row['slug'],
        'description': row.get('description'),
        'price': float(row['price']),
        'original_price': float(row['original_price']) if row.get('original_price') else None,
        'category': row['category'],
        'club': row.get('club'),
        'gender': row.get('gender', 'men'),
        'sizes': row.get('sizes') or [],
        'image_url': row.get('image_url'),
        'images': row.get('images') or ([row['image_url']] if row.get('image_url') else []),
        'features': row.get('features') or [],
        'composition': row.get('composition'),
        'is_new': row.get('is_new', False),
        'is_bestseller': row.get('is_bestseller', False),
        'is_featured': row.get('is_featured', False),
        'is_on_sale': row.get('is_on_sale', False),
        'stock': row.get('stock', 0),
        'size_stock': row.get('size_stock') or {},
        'rating': row.get('rating', 0.0),
        'reviews_count': row.get('reviews_count', 0),
        'created_at': row['created_at'].isoformat() if row.get('created_at') else None,
    }
